.Dd $Mdocdate$
.Dt MZ 1
.Os
.Sh NAME
.Nm mz
.Nd portmaster password recovery tool 
.Sh SYNOPSIS
.\" For a program:  program [-abc] file ...
.Nm
.Op Fl hq
.Ar CHALLENGE
.Sh DESCRIPTION
This is a little tool to recover password from Portmaster devices.
It was tested with several devices like PM2e PM3 PM4.
It should also work with other devices that uses similar recovery scheme.
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Mt pmsac@toxyn.org .

